version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9310:9310"
    depends_on:
      - mongodb
      - redis
    environment:
      - PORT=9310
      - DB_URL=mongodb://mongodb:27017/translate
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data_container:
  redis_data:
