version: '3.8'

services:
  app:
    build: .
    ports:
      - "9310:9310"
    environment:
      - PORT=9310
      - MONGODB_URI=your-mongodb-uri
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - .:/app
    command: npm start

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"